# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jemoji

permalink: /:year/:month/:title.html

# Site settings
title: "Tomek on Software"
description: > # this means to ignore newlines until "email:"
  Software - shaken, not stirred

email: tomasz@janczuk.org
logo: "/assets/images/logo.png"
cover: "/assets/images/b_2.jpg"

name: "Tomasz Janczuk"
author: "Tomasz Janczuk"
author_image: "/assets/images/tj.png"

paginate: 10

url: "https://tomasz.janczuk.org" # the base hostname & protocol for your site
enforce_ssl: tomasz.janczuk.org # without any protocol
baseurl: ""

# social icons and sharing options
social:
  - icon: twitter
    url: https://twitter.com/tjanczuk
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon: facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="
    # url: https://facebook.com/???
    # desc: Connect with me facebook

  - icon: github
    url: https://github.com/tjanczuk
    desc: Fork me on github
    # share_url:
    # share_title:
    # share_link:
