# Site settings
title: Tomek on Software
email: tomasz@janczuk.org
description: > # this means to ignore newlines until "baseurl:"
  Software: shaken, not stirred
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tomasz.janczuk.org" # the base hostname & protocol for your site
twitter_username: tjanczuk
github_username:  tjanczuk

# Build settings
markdown: kramdown
